### ISSUE TITLE
Migration exceptions starting a clean xchem/fragalysis-stack:2.0.0 conatiner

### ISSUE THREAD

**Issue by alanbchristie** [xchem/fragalysis-stack#46]
_I'm launching `xchem/fragalysis-stack:2.0.0`"cold", i.e fresh deployment, empty database._

Getting **django.contrib.auth.models.DoesNotExist: User matching query does not exist** exception during the initial migration, which takes place as the stack container starts.

Although the stack container images starts there are exceptions during the data migration stage which look serious and probably should be fixed. The full stack log is attached but the first exception is shown below: -

```
2020-09-22T13:04:56.701971214Z Operations to perform:
2020-09-22T13:04:56.702040357Z   Apply all migrations: viewer
2020-09-22T13:04:56.722079828Z Running migrations:
2020-09-22T13:04:56.982359684Z   Applying contenttypes.0001_initial... OK
2020-09-22T13:04:57.795490666Z   Applying auth.0001_initial... OK
2020-09-22T13:05:02.496417457Z   Applying viewer.0001_initial... OK
2020-09-22T13:05:02.75391939Z   Applying viewer.0002_target_zip_archive... OK
2020-09-22T13:05:03.200757414Z   Applying viewer.0003_auto_20200804_1241... OK
2020-09-22T13:05:03.344376673Z   Applying viewer.0004_auto_20200804_1411... OK
2020-09-22T13:05:03.633734733Z Traceback (most recent call last):
2020-09-22T13:05:03.635918826Z   File "/usr/local/lib/python3.7/dist-packages/guardian/management/__init__.py", line 32, in create_anonymous_user
2020-09-22T13:05:03.635958956Z     User.objects.using(kwargs['using']).get(**lookup)
2020-09-22T13:05:03.635971365Z   File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 431, in get
2020-09-22T13:05:03.636128109Z     self.model._meta.object_name
2020-09-22T13:05:03.636159122Z django.contrib.auth.models.DoesNotExist: User matching query does not exist.
```

The exception causes other exceptions, as you see `During handling of the above exception, another exception occurred:`

- **psycopg2.errors.NotNullViolation: null value in column "last_login" violates not-null constraint**
- **django.db.utils.IntegrityError: null value in column "last_login" violates not-null constraint**

There are also a rather large number of data warnings so an inspection of the data migrations looks necessary.

[stack-2.0.0.log](https://github.com/xchem/fragalysis-stack/files/5261731/stack-2.0.0.log)

**Comment by reskyner** [comment]
Note to self:
https://stackoverflow.com/questions/33683619/null-value-in-column-last-login-violates-not-null-constraint

**Comment by alanbchristie** [comment]
For information, the error is still present in the `2.0.3` image.

**Comment by reskyner** [comment]
I'm not seeing the error locally, or on the CI builds. I'll have to look into it further.

**Comment by reskyner** [comment]
Actually - I released v2.0.4 of the stack - this issue should be fixed there. Note the warnings are not fixed. The warnings will be more complicated to fix, as they involve changing the models, which is usually problematic...

**Comment by alanbchristie** [comment]
Agreed - the warnings need model adjustments and a new set of migration files. Too late for that now - it's too risky (unwise) to change these now.

For future - maybe we can avoid any new warnings. Otherwise there's a danger users will just get "desensitised" to the content of the log. A policy of no warnings (and certainly no errors) in the log is a good principle.

**Comment by alanbchristie** [comment]
Old issue - not longer applies
